### model
model_name_or_path: /root/autodl-tmp/Hugging-Face/models/DeepSeek-R1-Distill-Qwen-7B
trust_remote_code: true
# 加载第一步的 SFT 适配器
adapter_name_or_path: /root/autodl-tmp/LLaMA-Factory/saves/DeepSeek-R1-Distill-Qwen-7B/lora/sft-01  # 直接指定适配器路径

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 96
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
# deepspeed: examples/deepspeed/ds_z2_config.json # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
deepspeed: examples/deepspeed/ds_z2_offload_config.json

### dataset
dataset: medical_reward_top3500
template: deepseekr1
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 80
dataloader_num_workers: 20

### output
output_dir: saves/DeepSeek-R1-Distill-Qwen-7B/lora/dpo-01
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: dpo_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
